[package]
name = "blockchain"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
serde = {"version" = "1.0.183", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
xxhash-rust = { version = "0.8.15", features = ["xxh64"] }
